### ISSUE TITLE
Recording total consumption (today, last 7 days, last 30 days)

### ISSUE THREAD

**Issue by startedfromtheb0ttom** [Amadeaus-dll/HS110-Grafana#1]
Hello,
First: Thanks for the python script.

I would like to record in addition to the current consumption the total consumption of today, the last 7 days and the last 30 days. These are also displayed in the TP-Link Kasa app.

I tried influxdbexporter.py to expand, but unfortunately without success

**Comment by Amadeaus-dll** [comment]
Will add the feature today or tomorrow.

**Comment by startedfromtheb0ttom** [comment]
I've seen that the pull request from @StevenSeifried covers part of it. Please merge
